export const data = {
  bio: {
    name: "Leigh Halliday",
    tagline: "Full-Stack Developer",
    email: "leigh@email.com",
    github: "https://github.com/leighhalliday",
    website: "https://www.leighhalliday.com",
    linkedin: "https://linkedin.com/in/leigh-halliday",
    objective: "To build the greatest YouTube tutorials.",
  },
  skills: ["Speaking Spanish", "Certified coffee grower", "Visual Basic 6"],
  positions: [
    {
      id: "1",
      title: "Director of Engineering",
      company: "FlipGive",
      startDate: "2019-11-01",
      endDate: null,
      employmentType: "FULL_TIME",
      location: "Toronto, Canada",
      achievements: [
        "Mentoring developers, running 1 on 1s, finding training opportunities, leading developer peer group within OneEleven, organizing team lunch and learns",
        "Hiring, aligning engineering resources with business plans, develop career paths and align them with compensation",
        "Development of Ruby on Rails and React applications, working with GraphQL, Postgres, Redis",
      ],
    },
    {
      id: "2",
      title: "Lead Developer",
      company: "FlipGive",
      startDate: "2019-05-01",
      endDate: "2019-11-01",
      employmentType: "FULL_TIME",
      location: "Toronto, Canada",
      achievements: [
        "Building a large Ruby on Rails application powering www.flipgive.com + GraphQL API",
        "Working with React, TypeScript, Next.js and Apollo to build interactive websites.",
        "Creating and deploying serverless functions.",
      ],
    },
    {
      id: "3",
      title: "Senior Software Consultant",
      company: "FlipGive",
      startDate: "2017-03-01",
      endDate: "2019-05-01",
      employmentType: "FULL_TIME",
      location: "Toronto, Canada",
      achievements: [
        "Building a large Ruby on Rails application powering www.flipgive.com + GraphQL API",
        "Working with React, TypeScript, Next.js and Apollo to build interactive websites.",
        "Creating and deploying serverless functions.",
      ],
    },
    {
      id: "4",
      title: "Senior Software Developer",
      company: "Arcus",
      startDate: "2016-02-01",
      endDate: "2017-03-01",
      employmentType: "FULL_TIME",
      location: "New York, United States",
      achievements: [
        "Developing APIs and integrations using Ruby on Rails to help consumers manage their family's bills anywhere in the world.",
      ],
    },
    {
      id: "5",
      title: "Developer",
      company: "theScore",
      startDate: "2015-08-01",
      endDate: "2016-02-01",
      employmentType: "FULL_TIME",
      location: "Toronto, Canada",
      achievements: [
        "I work with sports data. Processing incoming data feeds, building admin management systems and APIs which are consumed by iOS, Android, and Web clients. Technologies involved are Ruby on Rails, Python and MySQL.",
      ],
    },
  ],
};
